#!/bin/bash -ue
#
# install - Instalador para os programas da Receita Federal (IRPF) no GNU/Linux
#
#    Copyright (C) 2015 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>
#
# Possui as seguintes características (e vantagens sobre o instalador oficial):
# - Download automatico dos programas, de qualquer ano desde 2008, sem
#     necessidade de navegar no site da RF.
# - Verificação de integridade do download através de checksums pré-computados.
# - Não necessita de privilégios adminstrativos para instalação.
# - Instala o Receitanet e o IRPF em uma única etapa.
# - Instala corretamente ícones e entradas de menu.
# - Não utiliza GUI, podendo ser automatizado para instalação em massa do IRPF
#     de vários anos

# Default options -------------------------------------------------------------

# Install root path
rootdir="$HOME"/.local/opt/ProgramasRFB

# Download path
download="$rootdir"/download

# Desktop files base dir
desktopbase=xdg

# Receitanet dir basename
receitanetbase=Receitanet

# Vendor prefix for xdg icons and desktop files
vendor=RFB

# IRPF
year=$(date +%Y)
irpfprefix=IRPF

# Main icon
iconprefix=rfb
iconsizes=(32 64 512)

# Uninstall flags
uninstall=0
purge=0

# Other options
verbose=1
force=0
yes=0
desktop=0
helpmenu=0
readmemenu=0

# Constants and other globals -------------------------------------------------

myname=${0##*/}
mydir=$(dirname "$(readlink -f "$0")")

oldyear=2008
minyear=2015
maxyear=$year
receitanet=0
irpf=0
archive=""
javacmd=(/usr/bin/java -Xms128m -Xmx256m -jar)
recver=""
regver=""
regpaths=('br/gov/serpro/receitanet'{,'/suite'})

checksumfile="$mydir"/sha256sum.txt

# Helper functions ------------------------------------------------------------

bold()    { tput bold; printf '%s' "$@"; tput sgr0; }
red()     { tput setaf 1; bold "$@"; }
green()   { tput setaf 2; bold "$@"; }

fatal()   { (($#)) && echo "$(red "$@")" >&2 || :; exit 1; }
message() { ((verbose)) && echo "$(green '* ' "$@")" || :; return; }
argerr()  { echo "$myname: erro${1:+: $(printf '%s' "$@")}" >&2 ; usage 1 ; }
invalid() { argerr "opção inválida: $1" ; }
missing() { argerr "está faltando um operando${1:+ em '$1'}." ; }
integer() { [[ "${1:-}" != *[!0-9]* ]] ||
            argerr "'$1' não é um ano válido."; }
yesno()   { if (($1)); then green "Sim"; else red "Não"; fi; }
linefeed(){ ((verbose)) && echo; }
cmdpath() { type -P "$1"; }

confirm()
{
	local message=$(bold "${1:-"Confirma?"}")
	local default=$(bold "NÃO")
	local reply

	if ! ((yes)); then
		linefeed
		read -p "$message (s/n, padrão $default): " reply
		reply="${reply:-$default}"
		case "$reply" in
		[YySs]*) ;;
		*) message "cancelado pelo usuário"; exit 1;;
		esac
	fi
}

usage() {
	cat <<- USAGE
	Uso: $myname [opções]
	USAGE
	if [[ "${1:-}" ]] ; then
		cat >&2 <<- USAGE
		Tente '$myname --help' para mais informações.
		USAGE
		exit 1
	fi
	cat <<USAGE

Instalador para os programas da Receita Federal (IRPF e ReceitaNet)

Inclui download dos programas, verificação de integridade, entradas de menu com
ícones oficiais, instalação e remoção sem necessidade de privilégios
admistrativos (root).

Testado com todos os programas da Receita desde 2008.

Opções gerais:
  -h|--help  - Exibe esta página de ajuda.
  -q|--quiet - Não exibe mensagens informativas, como o progresso da instalação.
  -y|--yes   - Automaticamente responde SIM a todas as perguntas de confirmação.
  -f|--force - Força ações mesmo que sejam redundantes, por exemplo instalação
               de programas já existentes (sobrescrevendo arquivos) ou a remoção
               de programas inexistentes.

Opções de pasta:
  --rootdir PATH
	Raiz comum da pasta de instalação dos programas.
	Cada programa, IRPF de cada ano ou ReceitaNet, será instalado em uma
	subpasta desta raiz.  O padrão é '$rootdir'

  --download PATH
	Pasta para download dos programas.
	O padrão é '$download'

Opções de instalação:
  --irpf ANO
	Instala o IRPF de um ano específico.

  --receitanet
	Instala (ou atualiza) a versão mais atual do ReceitaNet.

Se nenhuma das opções de instalação acima forem selecionadas, por padrão instala
tanto o ReceitaNet quanto o IRPF do ano atual, $year.

Opções de menus:
  --menu-ajuda
	Cria a entrada de menu para a 'Ajuda', um documento em formato PDF.
	O mesmo conteúdo desta Ajuda também está disponível em outro formato,
	a partir do próprio programa do IRPF, selecionando Ajuda -> Conteúdo,
	portanto esta entrada de menu é redundante.

  --menu-leiame
	Cria a entrada de menu para o 'Leia-me'. Contém apenas instruções da
	Receita para instalação do IRPF e da máquina virtual Java, com ênfase no
	ambiente Windows, sendo portanto desnecessária em ambiente GNU/Linux.

  --desktop
	Além das entradas de menu, cria também ícones na área de trabalho.

Opções de remoção:
  --uninstall
	Remove o ReceitaNet ou o IRPF de um ano específico.
	Deve ser utilizada em conjunto com --receitanet ou --irpf ANO.

  --uninstall-all
	Remove todos os programas da Receita.
	Não deve ser utilizado com nenhuma outra opção além de --rootdir.
	Por segurança, o uso em conjunto com --irpf, --receitanet ou --uninstall
	resulta em erro. Demais opções são ignoradas.

Copyright (C) 2015 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
Licença: GPLv3 ou posterior. Consulte <http://www.gnu.org/licenses/gpl.html>
USAGE
	exit 0
}

# Command-line argument parsing   ---------------------------------------------

for arg in "$@"; do case "$arg" in -h|--help) usage ;; esac; done
while (( $# )); do
	case "$1" in
	-h|--help	) usage;;
	-q|--quiet	) verbose=0;;
	-y|--yes	) yes=1;;
	-f|--force	) force=1;;
	--uninstall	) uninstall=1;;
	--uninstall-all	) purge=1;;
	--menu-ajuda	) helpmenu=1;;
	--menu-leiame	) readmemenu=1;;
	--desktop	) desktop=1;;
	--receitanet	) receitanet=1;;

	--rootdir=*	) rootdir="${1#*=}";;
	--rootdir	) shift; rootdir="${1:-}";;

	--download=*	) download="${1#*=}";;
	--download	) shift; download="${1:-}";;

	--irpf=*	) year="${1#*=}"; irpf=1;;
	--irpf  	) shift; year="${1:-}"; irpf=1;;

	*) invalid "$1"; break  ;;
	esac
	shift || :
done

[[ "$rootdir" ]]  || missing "--rootdir"
[[ "$download" ]] || missing "--download"
integer "$year" "--irpf"

if ((purge)); then
	if ((receitanet || irpf || uninstall)); then
		argerr "--uninstall-all remove todos os programas instalados." \
			" Para remover programas específicos,"                 \
			" utilize --uninstall."
	fi
elif !((receitanet)) && !((irpf)); then
	if ((uninstall)); then
		argerr "Para remover é necessário especificar --irpf ANO" \
			" ou --receitanet"
	else
		receitanet=1
		irpf=1
	fi
fi

if ((year < minyear)); then
	argerr "Para anos entre $oldyear e $((minyear-1))," \
		" utilize a versão antiga do instalador, install.old"
fi

if ((year > maxyear)) || ((year < minyear)); then
	argerr "Ano deve estar entre $minyear e $maxyear"
fi

# Derived vars ----------------------------------------------------------------

receitanetdir="$rootdir"/"$receitanetbase"
regjar="$receitanetdir"/lib/util-instalador.jar

irpfbase="${irpfprefix}${year}"
irpfdir="$rootdir"/"$irpfbase"

desktopdir="$rootdir"/"$desktopbase"
rootmenu="$desktopdir"/"$vendor"-ProgramasRFB.directory
xdg_desktop_menu="$desktopdir"/xdg-desktop-menu

iconname="${vendor}-${iconprefix}"

# Summary and confirmation ----------------------------------------------------

if ((verbose)); then
	message "Opções selecionadas:"
	if ((purge)); then
		echo $(red "REMOVER TODOS OS PROGRAMAS")
	elif ((uninstall)); then
		echo $(red "REMOVER")
	fi
	if !((purge)); then
		if ((irpf)); then
			echo "Programa do IRPF:   $(green $year)"
		else
			echo "Programa do IRPF:   $(red Não)"
		fi
			echo "Receitanet:         $(yesno $receitanet)"
		if !((uninstall)); then
			echo "Ícones no Desktop:  $(yesno $desktop)"
			echo "Inclui menu Ajuda:  $(yesno $helpmenu)"
			echo "Inclui menu Leiame: $(yesno $readmemenu)"
			echo "Pasta downloads:    $download"
		fi
	fi
			echo "Pasta principal:    $rootdir"
fi
confirm
linefeed

# Uninstall -------------------------------------------------------------------

purge(){
	local folder
	local iconsize

	if ! uninstall_check_dir "$rootdir" "principal"; then
		return
	fi

	shopt -s nullglob
	for folder in "$rootdir"/"$irpfprefix"*; do
		uninstall_irpf "$(basename "$folder")"
	done

	uninstall_receitanet

	message "Removendo pasta raiz e menu principal"

	# Icone principal
	for iconsize in "${iconsizes[@]}"; do
		xdg-icon-resource uninstall --noupdate \
			--size "$iconsize" "$iconname"
	done

	# Diretorio raiz
	rm -rf "$rootdir"
}

uninstall_check_dir() {
	local checkdir=$1
	local name=${2:-}
	local silent=${3:-0}

	if ((force)) || [[ -d "$checkdir" ]]; then
		return
	fi

	if !((silent)); then
		echo "Pasta ${name:+$name }'$checkdir' não existe." \
			"O programa já foi removido antes?" >&2
		echo "Use --force para forçar limpeza de ícones e menus" >&2
	fi
	return 1
}

uninstall_menus() {
	local deskfile

	patch_xdg && "$xdg_desktop_menu" uninstall --noupdate "$@"

	for deskfile in "$@"; do
		case "${deskfile##*.}" in
		desktop) xdg-desktop-icon uninstall "$deskfile";;
		esac
	done
}

uninstall_receitanet() {
	local icontitle
	local deskfiles=(
		"${rootmenu##*/}"
		"$vendor"-receitanet{.directory,{,-ajuda}.desktop}
	)

	if ! uninstall_check_dir "$receitanetdir" "do Receitanet" "$purge"; then
		return
	fi

	message "Removendo o Receitanet"

	# Receitanet - atalhos
	uninstall_menus "${deskfiles[@]}"

	# Receitanet - icones
	for icontitle in "${deskfiles[@]:2}"; do
		xdg-icon-resource uninstall --noupdate --size 32 "${icontitle%.*}"
	done

	# Limpa o registro Java
	if [[ -f "$regjar" ]]; then
		for regpath in "${regpaths[@]}"; do
			java -jar "$regjar" -limpar userRoot "$regpath" || true
		done
	fi

	# Receitanet - diretorio
	rm -rf "$receitanetdir"
}

uninstall_irpf() {
	local base="$1"
	local irpfdir="$rootdir"/"$base"
	local deskfiles=(
		"${rootmenu##*/}"
		"$vendor"-"${base,,}"{.directory,{,-{ajuda,leiame}}.desktop}
	)

	message "Removendo o $base"

	if ! uninstall_check_dir "$irpfdir" "do $base"; then
		return
	fi

	# Remove atalhos do menu e do desktop
	uninstall_menus "${deskfiles[@]}"

	# Remove o diretorio
	rm -rf "$irpfdir"
}

# Install helpers -------------------------------------------------------------

download_archive() {
	local atype="$1"
	local ftype
	local cksum
	local url
	local basefile
	local path
	local name
	local version
	local reg
	local q=()

	if !((verbose)); then
		q+=(--quiet)
	fi

	if [[ "$atype" == 'recnet' ]]; then
		name="a última versão do ReceitaNet"
	else
		name="o $irpfprefix $atype"
	fi

	while IFS="	" read -r -s ftype cksum url version reg; do
		if [[ -z "$url" ]] || ! [[ "$ftype" == "$atype" ]]; then
			continue
		fi
		basefile="${url##*/}"
		path="$download"/"$basefile"
		message "Baixando $name: $basefile"
		mkdir -p "$download"
		wget "${q[@]:+${q[@]}}" -P "$download" -N "$url" &&
		message "Verificando integridade do arquivo" &&
		sha256sum "${q[@]:+${q[@]}}" --check - <<< "$cksum  $path" ||
		fatal "Erro no download d$name de $url"
		archive=$path    # ugly use of a global var as return value
		break
	done < <(grep -v '^#' "$checksumfile" | LC_ALL=C sort -r -f -k 3)
	if [[ -z "$archive" ]]; then
		fatal "O arquivo para $name ainda não foi cadastrado!"
	fi
	if [[ "$atype" == 'recnet' ]]; then
		recver=$version  # ditto
		regver=$reg
	fi
}

empty_dir() {
	local path=$1
	if !((force)) && [[ -e "$path" ]]; then
		fatal "A pasta '$path' já existe!"          \
			" Utilize --uninstall para remover o programa" \
			" ou --force para sobrescrever arquivos."
	fi
	rm -rf "$path"
	mkdir -p "$path"
}

install_menus() {
	local deskfile

	# Menu entries
	patch_xdg && "$xdg_desktop_menu" install --noupdate "$@"

	# Desktop icons
	if ((desktop)); then
		for deskfile in "$@"; do
			if [[ "${deskfile##*.}" == 'desktop' ]]; then
				xdg-desktop-icon install "$deskfile"
			fi
		done
	fi
}

# Install functions -----------------------------------------------------------

# Patch xdg-desktop-menu to fix bug when handling filenames with spaces
# Using xdg official fix from its git repository at
# http://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=c96d7b00aca3da1b608fde5
# See https://bugs.freedesktop.org/show_bug.cgi?id=66605
# and https://bugs.freedesktop.org/show_bug.cgi?id=69339
patch_xdg() {
	if [[ -r "$xdg_desktop_menu" ]]; then
		# Assume it's already patched
		return
	fi

	local version="1.0.2"
	local xdgdesktopmenu="$(cmdpath xdg-desktop-menu)" ||
		fatal "'xdg-desktop-menu' não foi encontrado!" \
			" Instale o pacote xdg-utils."

	# Copy and patch only the known buggy version, otherwise symlink it
	mkdir -p "${xdg_desktop_menu%/*}/"
	if [[ "$("$xdgdesktopmenu" --version | cut -d' ' -f2)" == "$version" ]]
	then
		{ cat - "$xdgdesktopmenu" <<-EOF
		#!/bin/sh
		#
		# Patched by IRPF Installer - https://github.com/MestreLion/irpf
		# to fix bug when handling filenames with spaces, using official
		# fix from xdg upstream git repository at
		# http://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=c96d7b00a
		# See https://bugs.freedesktop.org/show_bug.cgi?id=66605
		# and https://bugs.freedesktop.org/show_bug.cgi?id=69339
		#
		EOF
		} |
		sed "/' \$menu_file >/s/ \$menu_file / \"\$menu_file\" /" |
		sed "s/${version}/${version}-patched/" > "$xdg_desktop_menu"
		chmod +x "$xdg_desktop_menu"
	else
		ln -s "$xdgdesktopmenu" "$xdg_desktop_menu"
	fi
}

install_root() {
	local icon

	if !((force)) && [[ -d "$desktopdir" ]]; then
		return
	fi

	message "Criando ícone e menu principal"

	mkdir -p "$desktopdir"

	# Menu
	cat > "$rootmenu" <<-EOF
		[Desktop Entry]
		Version=1.0
		Type=Directory
		Name=Imposto de Renda
		Comment=Receita Federal do Brasil
		Icon=$iconname
	EOF

	# Icons
	for iconsize in "${iconsizes[@]}"; do
		icon="$mydir"/icons/"${iconprefix}-${iconsize}.png"
		cp "$icon" "$desktopdir"/"${vendor}-${icon##*/}"
		xdg-icon-resource install --noupdate \
			--size "$iconsize" "$icon" "$iconname"
	done
}

install_receitanet() {
	empty_dir "$receitanetdir"
	download_archive 'recnet'

	message "Instalando o Receitanet $recver"

	dpkg-deb --fsys-tarfile "$archive" |
	tar -x --strip-components 4 --directory "$receitanetdir" \
		'./opt/Programas RFB/Receitanet/'

	# Grava no registro Java
	local regpath
	local regargs=(
		-escrever userRoot REGPATH_DUMMY
		Path "$receitanetdir"
		Origem A
		Tipo suite
		Versao "$regver"
		Instalacao D
	)
	for regpath in "${regpaths[@]}"; do
		regargs[2]="$regpath"
		java -jar "$regjar" "${regargs[@]}" || true
	done

	local deskprefix="$desktopdir"/"$vendor"-receitanet
	local recnetdeskfiles=(
		"$rootmenu"
		"$deskprefix".{directory,desktop}
	)

	cat > "${recnetdeskfiles[1]}" <<-EOF
		[Desktop Entry]
		Version=1.0
		Type=Directory
		Name=Receitanet
		Icon=$vendor-receitanet
	EOF

	cat > "${recnetdeskfiles[-1]}" <<-EOF
		[Desktop Entry]
		Version=1.0
		Type=Application
		Terminal=false
		Exec=${javacmd[@]} '${receitanetdir}/receitanet.jar'
		Name=Receitanet $recver
		Comment=Imposto de Renda - Receitanet
		GenericName=Receita Federal
		Icon=$vendor-receitanet
	EOF

	xdg-icon-resource install --noupdate --size 32    \
		"${receitanetdir}/imagens/Receitanet.xpm" \
		"$(basename "${recnetdeskfiles[-1]%.*}")"

	if ((helpmenu)); then
		recnetdeskfiles+=("$deskprefix"-ajuda.desktop)

		cat > "${recnetdeskfiles[-1]}" <<-EOF
			[Desktop Entry]
			Version=1.0
			Type=Application
			Terminal=false
			Exec=${javacmd[@]} '${receitanetdir}/receitanet.jar' -ajuda
			Name=Ajuda do Receitanet $recver
			GenericName=Receita Federal
			Icon=$vendor-receitanet-ajuda
		EOF

		xdg-icon-resource install --noupdate --size 32 \
			"${receitanetdir}/imagens/Ajuda.xpm"   \
			"$(basename "${recnetdeskfiles[-1]%.*}")"
	fi

	install_menus "${recnetdeskfiles[@]}"
}

install_irpf() {
	empty_dir "$irpfdir"
	download_archive "$year"

	message "Instalando o $irpfprefix $year"

	# Extract the zip file.
	# Cannot extract directly to $rootdir as not all zips have top-level dir
	# in the IRPF2000 format used as install basename: some are irpf2000
	# or IRPF-2000. --strip-components is the solution, but unzip has no
	# such option, so we extract to a tempdir and use tar to repack and
	# extract it on-the-fly to final destination.
	local tempdir="$download"/temp
	rm -rf "$tempdir"
	unzip -q "$archive" -d "$tempdir"
	tar --directory "$tempdir" -c . |
	tar --directory="$irpfdir" -x --strip-components=2
	rm -rf "$tempdir"

	local deskprefix="$desktopdir"/"$vendor"-"${irpfbase,,}"
	local irpfdeskfiles=(
		"$rootmenu"
		"$deskprefix".{directory,desktop}
	)

	cat > "${irpfdeskfiles[1]}" <<-EOF
		[Desktop Entry]
		Version=1.0
		Type=Directory
		Name=${irpfbase^^}
		Icon=$iconname
	EOF

	cat > "${irpfdeskfiles[-1]}" <<-EOF
		[Desktop Entry]
		Version=1.0
		Type=Application
		Name=${irpfbase^^} - Declaração Anual
		Comment=Imposto de Renda $year
		GenericName=Receita Federal
		Exec=${javacmd[@]} '${irpfdir}/irpf.jar'
		Icon=$iconname
	EOF

	if ((helpmenu)); then
		irpfdeskfiles+=("$deskprefix"-ajuda.desktop)
		cat > "${irpfdeskfiles[-1]}" <<-EOF
			[Desktop Entry]
			Version=1.0
			Type=Application
			Name=Ajuda do ${irpfbase^^}
			Comment=Imposto de Renda $year
			GenericName=Receita Federal
			Exec=xdg-open '${irpfdir}/help/AjudaIRPF.pdf'
			Icon=$iconname
		EOF
	fi

	if ((readmemenu)); then
		irpfdeskfiles+=("$deskprefix"-leiame.desktop)
		cat > "${irpfdeskfiles[-1]}" <<-EOF
			[Desktop Entry]
			Version=1.0
			Type=Application
			Name=Leia-me do ${irpfbase^^}
			Comment=Imposto de Renda $year
			GenericName=Receita Federal
			Exec=xdg-open '${irpfdir}/Leia-me.htm'
			Icon=$iconname
		EOF
	fi

	install_menus "${irpfdeskfiles[@]}"
}

# Main procedures and logic ---------------------------------------------------

if ((purge)); then
	purge
elif ((uninstall)); then
	if ((receitanet)); then uninstall_receitanet; fi
	if ((irpf));       then uninstall_irpf "$irpfbase"; fi
else
	install_root
	if ((receitanet)); then install_receitanet; fi
	if ((irpf));       then install_irpf; fi
fi

# Aplica todas as atualizacoes
xdg-icon-resource forceupdate
xdg-desktop-menu  forceupdate
message "Pronto!"
